// ============================================================
//  B-CHAT  —  Shared Configuration
//  Update these values with your own credentials
// ============================================================

const BCHAT_CONFIG = {
  SUPABASE_URL:    'https://vfkwmbjxfealiadkjuld.supabase.co',
  SUPABASE_ANON:   'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZma3dtYmp4ZmVhbGlhZGtqdWxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2NzA1MTcsImV4cCI6MjA4OTI0NjUxN30.m-d6CLvfc9VOY8fS_Lr2gfbLiHsMfojpT-lyJk7Slbc',
  GROQ_API_KEY:    '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',           // Platform-level key
  GROQ_MODEL:      'qwen/qwen3-32b',
  BASE_URL:        'https://your-domain.com',      // or localhost path
  APP_NAME:        'B-Chat',
  DEFAULT_COLOR:   '#6366f1',
};

// ── TRANSLATIONS ─────────────────────────────────────────────
const I18N = {
  en: {
    dir: 'ltr',
    hero_title: 'Your AI Sales Assistant,',
    hero_highlight: 'Ready in Minutes.',
    hero_sub: 'Build a personalized AI chatbot trained on your products. Convert visitors into buyers — 24/7, automatically.',
    cta_trial: 'Start 30-Day Free Trial',
    cta_demo: 'See Live Demo',
    feat_title: 'Everything You Need to Sell',
    feat1_title: 'Instant AI Setup',
    feat1_desc: 'Train your bot on your products in under 5 minutes. No coding required.',
    feat2_title: 'Multilingual Support',
    feat2_desc: 'Responds fluently in Arabic, English, French, Spanish, German & Swedish.',
    feat3_title: 'Full Customization',
    feat3_desc: 'Brand it with your logo, colors, and unique personality.',
    feat4_title: 'Smart Analytics',
    feat4_desc: 'Track conversations, message usage, and customer interactions.',
    feat5_title: 'One-Link Deploy',
    feat5_desc: 'Get a shareable link. Add it to Instagram bio, website, or WhatsApp.',
    feat6_title: 'Secure & Reliable',
    feat6_desc: 'Built on Supabase & Groq. Enterprise-grade uptime and security.',
    price_title: 'Simple, Transparent Pricing',
    plan_free: 'Free Trial',
    plan_free_price: '$0',
    plan_free_period: '/ 30 days',
    plan_pro: 'Pro',
    plan_pro_price: '$19',
    plan_pro_period: '/ month',
    plan_messages: '1,000 messages included',
    plan_topup: 'Top-up packs available',
    login: 'Login',
    register: 'Register',
    email: 'Email Address',
    password: 'Password',
    store_name: 'Store Name',
    have_account: 'Already have an account?',
    no_account: "Don't have an account?",
    logout: 'Logout',
    dashboard: 'Dashboard',
    days_left: 'days left',
    msgs_left: 'messages left',
    save: 'Save Changes',
    saved: 'Saved!',
    copy_link: 'Copy My Link',
    copied: 'Copied!',
    redeem_code: 'Redeem Code',
    redeem_placeholder: 'Enter activation code',
    tab_custom: 'Customize',
    tab_brain: 'Brain',
    tab_analytics: 'Analytics',
    tab_deploy: 'Deploy',
    tab_billing: 'Billing',
    products_info: 'Products & Info',
    products_placeholder: 'List your products, services, prices, policies...',
    custom_prompt: 'Custom Behavior Instructions',
    prompt_placeholder: 'e.g. Always respond in Arabic. Be friendly. Focus on selling X.',
    theme_color: 'Brand Color',
    bot_name: 'Bot Name',
    logo: 'Store Logo',
    upload_logo: 'Upload Logo',
    store_name_label: 'Store Name',
    trial_expired: 'Your trial has expired. Please renew.',
    no_messages: 'Message balance is zero. Please top up.',
    type_message: 'Type a message...',
    send: 'Send',
    thinking: 'Thinking...',
    your_name: 'Your Name (optional)',
    start_chat: 'Start Chatting',
    admin_panel: 'Admin Panel',
    merchants: 'Merchants',
    gen_code: 'Generate Code',
    code: 'Code',
    amount: 'Amount',
    used: 'Used',
    created: 'Created',
    actions: 'Actions',
    total_merchants: 'Total Merchants',
    active_subs: 'Active Subscriptions',
    total_messages: 'Messages Sent Today',
    copy: 'Copy',
    error_login: 'Invalid email or password.',
    error_register: 'Registration failed. Try again.',
    sub_expires: 'Subscription expires',
    bio: 'Store Description',
    bio_placeholder: 'Brief description of your store...',
  },
  ar: {
    dir: 'rtl',
    hero_title: 'مساعدك الذكي للمبيعات،',
    hero_highlight: 'جاهز في دقائق.',
    hero_sub: 'أنشئ روبوت محادثة مدرّب على منتجاتك. حوّل الزوار إلى مشترين — 24/7، تلقائياً.',
    cta_trial: 'ابدأ تجربة 30 يومًا مجانًا',
    cta_demo: 'شاهد العرض المباشر',
    feat_title: 'كل ما تحتاجه للبيع',
    feat1_title: 'إعداد فوري',
    feat1_desc: 'درّب الروبوت على منتجاتك في أقل من 5 دقائق. بدون أي كود.',
    feat2_title: 'دعم متعدد اللغات',
    feat2_desc: 'يجيب بطلاقة بالعربية والإنجليزية والفرنسية والإسبانية والألمانية والسويدية.',
    feat3_title: 'تخصيص كامل',
    feat3_desc: 'أضف شعارك وألوانك وشخصيتك المميزة.',
    feat4_title: 'تحليلات ذكية',
    feat4_desc: 'تتبع المحادثات واستخدام الرسائل وتفاعلات العملاء.',
    feat5_title: 'نشر برابط واحد',
    feat5_desc: 'احصل على رابط قابل للمشاركة. أضفه لبيو انستغرام أو موقعك أو واتساب.',
    feat6_title: 'آمن وموثوق',
    feat6_desc: 'مبني على Supabase و Groq. جاهزية وأمان بمستوى المؤسسات.',
    price_title: 'أسعار بسيطة وشفافة',
    plan_free: 'تجربة مجانية',
    plan_free_price: '$0',
    plan_free_period: '/ 30 يوم',
    plan_pro: 'برو',
    plan_pro_price: '$19',
    plan_pro_period: '/ شهر',
    plan_messages: '1,000 رسالة مشمولة',
    plan_topup: 'حزم إضافية متاحة',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    store_name: 'اسم المتجر',
    have_account: 'لديك حساب بالفعل؟',
    no_account: 'ليس لديك حساب؟',
    logout: 'تسجيل الخروج',
    dashboard: 'لوحة التحكم',
    days_left: 'يوم متبقي',
    msgs_left: 'رسالة متبقية',
    save: 'حفظ التغييرات',
    saved: 'تم الحفظ!',
    copy_link: 'نسخ رابطي',
    copied: 'تم النسخ!',
    redeem_code: 'استبدال الكود',
    redeem_placeholder: 'أدخل كود التفعيل',
    tab_custom: 'التخصيص',
    tab_brain: 'الذاكرة',
    tab_analytics: 'الإحصائيات',
    tab_deploy: 'النشر',
    tab_billing: 'الفوترة',
    products_info: 'المنتجات والمعلومات',
    products_placeholder: 'أدرج منتجاتك وخدماتك وأسعارك وسياساتك...',
    custom_prompt: 'تعليمات السلوك المخصصة',
    prompt_placeholder: 'مثال: أجب دائماً بالعربية. كن ودوداً. ركز على بيع X.',
    theme_color: 'لون العلامة التجارية',
    bot_name: 'اسم الروبوت',
    logo: 'شعار المتجر',
    upload_logo: 'رفع الشعار',
    store_name_label: 'اسم المتجر',
    trial_expired: 'انتهت فترة التجربة. يرجى التجديد.',
    no_messages: 'رصيد الرسائل صفر. يرجى الشحن.',
    type_message: 'اكتب رسالة...',
    send: 'إرسال',
    thinking: 'يفكر...',
    your_name: 'اسمك (اختياري)',
    start_chat: 'ابدأ المحادثة',
    admin_panel: 'لوحة الإدارة',
    merchants: 'التجار',
    gen_code: 'إنشاء كود',
    code: 'الكود',
    amount: 'الكمية',
    used: 'مستخدم',
    created: 'تاريخ الإنشاء',
    actions: 'الإجراءات',
    total_merchants: 'إجمالي التجار',
    active_subs: 'الاشتراكات النشطة',
    total_messages: 'الرسائل المرسلة اليوم',
    copy: 'نسخ',
    error_login: 'بريد إلكتروني أو كلمة مرور غير صحيحة.',
    error_register: 'فشل التسجيل. حاول مرة أخرى.',
    sub_expires: 'ينتهي الاشتراك',
    bio: 'وصف المتجر',
    bio_placeholder: 'وصف مختصر لمتجرك...',
  },
  fr: {
    dir: 'ltr',
    hero_title: 'Votre Assistant IA Commercial,',
    hero_highlight: 'Prêt en Minutes.',
    hero_sub: 'Créez un chatbot IA formé sur vos produits. Convertissez les visiteurs en acheteurs — 24h/24, automatiquement.',
    cta_trial: 'Essai Gratuit 30 Jours',
    cta_demo: 'Voir la Démo',
    feat_title: 'Tout ce qu\'il faut pour Vendre',
    feat1_title: 'Configuration Instantanée',
    feat1_desc: 'Formez votre bot sur vos produits en moins de 5 minutes. Aucun code requis.',
    feat2_title: 'Support Multilingue',
    feat2_desc: 'Répond couramment en arabe, anglais, français, espagnol, allemand et suédois.',
    feat3_title: 'Personnalisation Totale',
    feat3_desc: 'Brandez-le avec votre logo, vos couleurs et votre personnalité unique.',
    feat4_title: 'Analytiques Intelligentes',
    feat4_desc: 'Suivez les conversations, l\'utilisation des messages et les interactions.',
    feat5_title: 'Déploiement en Un Lien',
    feat5_desc: 'Obtenez un lien partageable. Ajoutez-le à votre bio Instagram, site ou WhatsApp.',
    feat6_title: 'Sécurisé et Fiable',
    feat6_desc: 'Construit sur Supabase & Groq. Disponibilité et sécurité de niveau entreprise.',
    price_title: 'Tarification Simple et Transparente',
    plan_free: 'Essai Gratuit',
    plan_free_price: '0$',
    plan_free_period: '/ 30 jours',
    plan_pro: 'Pro',
    plan_pro_price: '19$',
    plan_pro_period: '/ mois',
    plan_messages: '1 000 messages inclus',
    plan_topup: 'Packs de recharge disponibles',
    login: 'Connexion',
    register: 'S\'inscrire',
    email: 'Adresse Email',
    password: 'Mot de Passe',
    store_name: 'Nom de la Boutique',
    have_account: 'Déjà un compte?',
    no_account: 'Pas encore de compte?',
    logout: 'Déconnexion',
    dashboard: 'Tableau de Bord',
    days_left: 'jours restants',
    msgs_left: 'messages restants',
    save: 'Enregistrer',
    saved: 'Sauvegardé!',
    copy_link: 'Copier Mon Lien',
    copied: 'Copié!',
    redeem_code: 'Activer le Code',
    redeem_placeholder: 'Entrez le code d\'activation',
    tab_custom: 'Personnaliser',
    tab_brain: 'Cerveau',
    tab_analytics: 'Analytiques',
    tab_deploy: 'Déployer',
    tab_billing: 'Facturation',
    products_info: 'Produits & Infos',
    products_placeholder: 'Listez vos produits, services, prix, politiques...',
    custom_prompt: 'Instructions de Comportement',
    prompt_placeholder: 'ex: Répondre toujours en français. Être amical. Se concentrer sur X.',
    theme_color: 'Couleur de Marque',
    bot_name: 'Nom du Bot',
    logo: 'Logo de la Boutique',
    upload_logo: 'Télécharger Logo',
    store_name_label: 'Nom de la Boutique',
    trial_expired: 'Votre essai a expiré. Veuillez renouveler.',
    no_messages: 'Solde de messages épuisé. Veuillez recharger.',
    type_message: 'Écrire un message...',
    send: 'Envoyer',
    thinking: 'Réflexion...',
    your_name: 'Votre Nom (optionnel)',
    start_chat: 'Commencer',
    admin_panel: 'Panneau Admin',
    merchants: 'Marchands',
    gen_code: 'Générer un Code',
    code: 'Code',
    amount: 'Montant',
    used: 'Utilisé',
    created: 'Créé le',
    actions: 'Actions',
    total_merchants: 'Total Marchands',
    active_subs: 'Abonnements Actifs',
    total_messages: 'Messages Envoyés Aujourd\'hui',
    copy: 'Copier',
    error_login: 'Email ou mot de passe invalide.',
    error_register: 'Inscription échouée. Réessayez.',
    sub_expires: 'Abonnement expire le',
    bio: 'Description de la Boutique',
    bio_placeholder: 'Brève description de votre boutique...',
  },
  es: {
    dir: 'ltr',
    hero_title: 'Tu Asistente de Ventas IA,',
    hero_highlight: 'Listo en Minutos.',
    hero_sub: 'Crea un chatbot IA entrenado en tus productos. Convierte visitantes en compradores — 24/7, automáticamente.',
    cta_trial: 'Prueba Gratuita 30 Días',
    cta_demo: 'Ver Demo',
    feat_title: 'Todo lo que Necesitas para Vender',
    feat1_title: 'Configuración Instantánea', feat1_desc: 'Entrena tu bot en menos de 5 minutos.',
    feat2_title: 'Soporte Multilingüe', feat2_desc: 'Responde en árabe, inglés, francés, español, alemán y sueco.',
    feat3_title: 'Personalización Total', feat3_desc: 'Tu logo, colores y personalidad única.',
    feat4_title: 'Analíticas Inteligentes', feat4_desc: 'Rastrea conversaciones y uso de mensajes.',
    feat5_title: 'Despliegue con Un Enlace', feat5_desc: 'Comparte en Instagram, web o WhatsApp.',
    feat6_title: 'Seguro y Confiable', feat6_desc: 'Construido en Supabase & Groq.',
    price_title: 'Precios Simples y Transparentes',
    plan_free: 'Prueba Gratuita', plan_free_price: '$0', plan_free_period: '/ 30 días',
    plan_pro: 'Pro', plan_pro_price: '$19', plan_pro_period: '/ mes',
    plan_messages: '1,000 mensajes incluidos', plan_topup: 'Paquetes de recarga disponibles',
    login: 'Iniciar Sesión', register: 'Registrarse', email: 'Correo Electrónico', password: 'Contraseña',
    store_name: 'Nombre de la Tienda', have_account: '¿Ya tienes cuenta?', no_account: '¿No tienes cuenta?',
    logout: 'Cerrar Sesión', dashboard: 'Panel', days_left: 'días restantes', msgs_left: 'mensajes restantes',
    save: 'Guardar', saved: '¡Guardado!', copy_link: 'Copiar Mi Enlace', copied: '¡Copiado!',
    redeem_code: 'Canjear Código', redeem_placeholder: 'Ingresa el código de activación',
    tab_custom: 'Personalizar', tab_brain: 'Cerebro', tab_analytics: 'Analíticas',
    tab_deploy: 'Desplegar', tab_billing: 'Facturación',
    products_info: 'Productos e Info', products_placeholder: 'Lista tus productos, servicios, precios...',
    custom_prompt: 'Instrucciones de Comportamiento', prompt_placeholder: 'Ej: Responder siempre en español.',
    theme_color: 'Color de Marca', bot_name: 'Nombre del Bot', logo: 'Logo de la Tienda',
    upload_logo: 'Subir Logo', store_name_label: 'Nombre de la Tienda',
    trial_expired: 'Tu prueba ha expirado. Por favor renueva.',
    no_messages: 'Saldo de mensajes agotado. Por favor recarga.',
    type_message: 'Escribe un mensaje...', send: 'Enviar', thinking: 'Pensando...',
    your_name: 'Tu Nombre (opcional)', start_chat: 'Iniciar Chat',
    admin_panel: 'Panel de Administración', merchants: 'Comerciantes', gen_code: 'Generar Código',
    code: 'Código', amount: 'Cantidad', used: 'Usado', created: 'Creado', actions: 'Acciones',
    total_merchants: 'Total Comerciantes', active_subs: 'Suscripciones Activas',
    total_messages: 'Mensajes Enviados Hoy', copy: 'Copiar',
    error_login: 'Email o contraseña inválidos.', error_register: 'Registro fallido. Inténtalo de nuevo.',
    sub_expires: 'Suscripción expira', bio: 'Descripción de la Tienda', bio_placeholder: 'Breve descripción...',
  },
  de: {
    dir: 'ltr',
    hero_title: 'Dein KI-Verkaufsassistent,',
    hero_highlight: 'In Minuten bereit.',
    hero_sub: 'Erstelle einen KI-Chatbot, der auf deine Produkte trainiert ist. Wandle Besucher in Käufer um — 24/7, automatisch.',
    cta_trial: '30-Tage Gratis-Testversion',
    cta_demo: 'Live-Demo ansehen',
    feat_title: 'Alles was du brauchst',
    feat1_title: 'Sofort-Setup', feat1_desc: 'Bot in unter 5 Minuten trainieren.',
    feat2_title: 'Mehrsprachig', feat2_desc: 'Antwortet auf Arabisch, Englisch, Französisch, Spanisch, Deutsch & Schwedisch.',
    feat3_title: 'Volle Anpassung', feat3_desc: 'Dein Logo, Farben und Persönlichkeit.',
    feat4_title: 'Smart Analytics', feat4_desc: 'Gespräche und Nutzung verfolgen.',
    feat5_title: 'Ein-Link-Bereitstellung', feat5_desc: 'Teile auf Instagram, Website oder WhatsApp.',
    feat6_title: 'Sicher & Zuverlässig', feat6_desc: 'Gebaut auf Supabase & Groq.',
    price_title: 'Einfache, transparente Preise',
    plan_free: 'Gratis-Test', plan_free_price: '0$', plan_free_period: '/ 30 Tage',
    plan_pro: 'Pro', plan_pro_price: '19$', plan_pro_period: '/ Monat',
    plan_messages: '1.000 Nachrichten inklusive', plan_topup: 'Aufladepakete verfügbar',
    login: 'Anmelden', register: 'Registrieren', email: 'E-Mail', password: 'Passwort',
    store_name: 'Shop-Name', have_account: 'Bereits ein Konto?', no_account: 'Noch kein Konto?',
    logout: 'Abmelden', dashboard: 'Dashboard', days_left: 'Tage verbleibend', msgs_left: 'Nachrichten verbleibend',
    save: 'Speichern', saved: 'Gespeichert!', copy_link: 'Link Kopieren', copied: 'Kopiert!',
    redeem_code: 'Code Einlösen', redeem_placeholder: 'Aktivierungscode eingeben',
    tab_custom: 'Anpassen', tab_brain: 'Gehirn', tab_analytics: 'Analytik',
    tab_deploy: 'Bereitstellen', tab_billing: 'Abrechnung',
    products_info: 'Produkte & Info', products_placeholder: 'Produkte, Dienste, Preise, Richtlinien...',
    custom_prompt: 'Verhaltensanweisungen', prompt_placeholder: 'z.B.: Immer auf Deutsch antworten.',
    theme_color: 'Markenfarbe', bot_name: 'Bot-Name', logo: 'Shop-Logo',
    upload_logo: 'Logo hochladen', store_name_label: 'Shop-Name',
    trial_expired: 'Test abgelaufen. Bitte verlängern.',
    no_messages: 'Nachrichtenguthaben aufgebraucht. Bitte aufladen.',
    type_message: 'Nachricht schreiben...', send: 'Senden', thinking: 'Denkt nach...',
    your_name: 'Dein Name (optional)', start_chat: 'Chat starten',
    admin_panel: 'Admin-Panel', merchants: 'Händler', gen_code: 'Code Generieren',
    code: 'Code', amount: 'Menge', used: 'Verwendet', created: 'Erstellt', actions: 'Aktionen',
    total_merchants: 'Händler Gesamt', active_subs: 'Aktive Abonnements',
    total_messages: 'Heute gesendete Nachrichten', copy: 'Kopieren',
    error_login: 'Ungültige E-Mail oder Passwort.', error_register: 'Registrierung fehlgeschlagen.',
    sub_expires: 'Abonnement läuft ab', bio: 'Shop-Beschreibung', bio_placeholder: 'Kurze Beschreibung...',
  },
  sv: {
    dir: 'ltr',
    hero_title: 'Din AI-Säljassistent,',
    hero_highlight: 'Redo på Minuter.',
    hero_sub: 'Skapa en AI-chatbot tränad på dina produkter. Omvandla besökare till köpare — 24/7, automatiskt.',
    cta_trial: 'Starta 30-Dagars Gratis Test',
    cta_demo: 'Se Live Demo',
    feat_title: 'Allt du Behöver för att Sälja',
    feat1_title: 'Omedelbar Installation', feat1_desc: 'Träna boten på under 5 minuter.',
    feat2_title: 'Flerspråkigt Stöd', feat2_desc: 'Svarar på arabiska, engelska, franska, spanska, tyska och svenska.',
    feat3_title: 'Full Anpassning', feat3_desc: 'Din logotyp, färger och personlighet.',
    feat4_title: 'Smart Analys', feat4_desc: 'Spåra konversationer och meddelandeanvändning.',
    feat5_title: 'En-Länk Driftsättning', feat5_desc: 'Dela på Instagram, webbplats eller WhatsApp.',
    feat6_title: 'Säker & Tillförlitlig', feat6_desc: 'Byggd på Supabase & Groq.',
    price_title: 'Enkla, Transparenta Priser',
    plan_free: 'Gratis Test', plan_free_price: '0$', plan_free_period: '/ 30 dagar',
    plan_pro: 'Pro', plan_pro_price: '19$', plan_pro_period: '/ månad',
    plan_messages: '1 000 meddelanden ingår', plan_topup: 'Påfyllningspaket tillgängliga',
    login: 'Logga In', register: 'Registrera', email: 'E-postadress', password: 'Lösenord',
    store_name: 'Butiksnamn', have_account: 'Redan ett konto?', no_account: 'Inget konto?',
    logout: 'Logga Ut', dashboard: 'Dashboard', days_left: 'dagar kvar', msgs_left: 'meddelanden kvar',
    save: 'Spara', saved: 'Sparat!', copy_link: 'Kopiera Min Länk', copied: 'Kopierat!',
    redeem_code: 'Lös In Kod', redeem_placeholder: 'Ange aktiveringskod',
    tab_custom: 'Anpassa', tab_brain: 'Hjärna', tab_analytics: 'Analys',
    tab_deploy: 'Driftsätt', tab_billing: 'Fakturering',
    products_info: 'Produkter & Info', products_placeholder: 'Lista dina produkter, tjänster, priser...',
    custom_prompt: 'Beteendeinstruktioner', prompt_placeholder: 'T.ex.: Svara alltid på svenska.',
    theme_color: 'Varumärkesfärg', bot_name: 'Botnamn', logo: 'Butikslogotyp',
    upload_logo: 'Ladda upp logotyp', store_name_label: 'Butiksnamn',
    trial_expired: 'Din testperiod har gått ut. Förnya.',
    no_messages: 'Meddelandesaldot är noll. Ladda på.',
    type_message: 'Skriv ett meddelande...', send: 'Skicka', thinking: 'Tänker...',
    your_name: 'Ditt Namn (valfritt)', start_chat: 'Starta Chatt',
    admin_panel: 'Adminpanel', merchants: 'Handlare', gen_code: 'Generera Kod',
    code: 'Kod', amount: 'Mängd', used: 'Använd', created: 'Skapad', actions: 'Åtgärder',
    total_merchants: 'Totala Handlare', active_subs: 'Aktiva Prenumerationer',
    total_messages: 'Meddelanden Skickade Idag', copy: 'Kopiera',
    error_login: 'Ogiltig e-post eller lösenord.', error_register: 'Registrering misslyckades.',
    sub_expires: 'Prenumeration löper ut', bio: 'Butiksbeskrivning', bio_placeholder: 'Kort beskrivning...',
  },
};

// ── LANGUAGE HELPERS ─────────────────────────────────────────
function getLang() {
  return localStorage.getItem('bchat_lang') || 'en';
}
function setLang(lang) {
  localStorage.setItem('bchat_lang', lang);
  applyLang(lang);
}
function t(key) {
  const lang = getLang();
  return (I18N[lang] && I18N[lang][key]) ? I18N[lang][key] : (I18N.en[key] || key);
}
function applyLang(lang) {
  const d = I18N[lang] || I18N.en;
  document.documentElement.setAttribute('dir', d.dir);
  document.documentElement.setAttribute('lang', lang);
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (d[key]) el.textContent = d[key];
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (d[key]) el.placeholder = d[key];
  });
}

// ── SUPABASE CLIENT FACTORY ──────────────────────────────────
function createSupabase() {
  return supabase.createClient(BCHAT_CONFIG.SUPABASE_URL, BCHAT_CONFIG.SUPABASE_ANON);
}
